apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: dev-nginx
spec:
  rules:
  - host: dev-nginx.fgn.nerdystar.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-nginx-service
            port:
              number: 80

