apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: dev-nginx
spec:
  rules:
  - host: dev-nginx.somaz.link
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-nginx-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1

