apiVersion: v1
kind: Service
metadata:
  name: qa-nginx-service
  namespace: qa-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-nginx-deployment
  namespace: qa-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: qa-nginx-ingress
  namespace: qa-nginx
spec:
  rules:
  - host: qa-nginx.somaz.link
    http:
      paths:
      - backend:
          service:
            name: qa-nginx-service
            port:
              number: 80
        path: /
        pathType: Prefix
