apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-nginx-deployment
  namespace: qa-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
