---
apiVersion: v1
kind: Secret
metadata:
  name: flux-ssh-key
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    ...
    0zbXo5J4Yb6oMAAAAUZ2VuaXVzNTcxMUBnbWFpbC5jb20BAgMEBQYH
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ssh-rsa AAAAB3...
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHN...

